const RESPONSE_CODE = {
    DEFAULT: "SUCCESS",
    LOGIN: "LOGIN",
    OTP: "OTP_VERIFIED",
    FORGOT_PASSWORD: "FORGOT_PASSWORD",
    ERROR: "ERROR",
    ALERTS: "ALERTS",
    UNAUTHENTICATED: "UNAUTHENTICATED",
    NOT_VERIFIED: "NOT_VERIFIED",
    DUPLICATE: "DUPLICATE",
    INVALID_CLIENT: "INVALID_CLIENT",
    FAILURE: "FAILURE",
    REDIRECT: "REDIRECT"
  };
  
  module.exports = {
    RESPONSE_CODE,
  };
  